apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overleaf-mongo
  namespace: argocd
spec:
  project: overleaf
  source:
    chart: mongodb
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 16.4.1
    helm:
      values: |
        arbiter:
          nodeSelector:
            kubernetes.io/arch: amd64
        architecture: "replicaset"
        auth:
          enabled: false
        nodeSelector:
          kubernetes.io/arch: amd64
  destination:
    server: https://kubernetes.default.svc
    namespace: overleaf
