apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: overleaf-redis
  namespace: argocd
spec:
  project: overleaf
  source:
    chart: redis
    repoURL: https://charts.bitnami.com/bitnami
    targetRevision: 20.8.0
    helm:
      values: |
        auth:
          enabled: false
  destination:
    server: https://kubernetes.default.svc
    namespace: overleaf
