apiVersion: v1
kind: Namespace
metadata:
  name: bazarr
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: bazarr
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: bazarr
  project: media
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/bazarr
