apiVersion: v1
kind: Namespace
metadata:
  name: sonarr
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: sonarr
  namespace: argocd
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: sonarr
  project: media
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/sonarr
  syncPolicy:
    automated: {}
