apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: sonarr
  labels:
    app: sonarr
spec:
  replicas: 1
  selector:
    matchLabels:
      app: sonarr
  serviceName: sonarr
  template:
    metadata:
      name: sonarr
      labels:
        app: sonarr
    spec:
      initContainers:
        - name: backup-sidecar
          image: ghcr.io/ansg191/containers/arr-backup:main@sha256:f7b7e5a4be5b7e2520629d00701beba89437487c9d1e1e08632af404fb190c18
          imagePullPolicy: IfNotPresent
          restartPolicy: Always
          volumeMounts:
            - mountPath: /rconfig
              name: config
            - mountPath: /tarsnapper.conf
              name: tarsnapper-config
              subPath: tarsnapper.conf
            - mountPath: /config/tarsnap.key
              name: backup-key
              subPath: tarsnap.key
            - mountPath: /backup
              name: backup-tmpdir
            - mountPath: /tarsnap-cache
              name: tarsnap-cache
          env:
            - name: ARR_CONFIG_DIR
              value: /rconfig
            - name: ARR_API_KEY
              valueFrom:
                secretKeyRef:
                  name: backup-key
                  key: api-key
            - name: ARR_URL
              value: http://localhost:8989
            - name: TARSNAPPER_CONFIG
              value: /tarsnapper.conf
            - name: ARR_TMP_DIR
              value: /backup
          securityContext:
            runAsUser: 0
            runAsGroup: 0
      containers:
        - name: sonarr
          image: lscr.io/linuxserver/sonarr:4.0.11@sha256:4ba3bfa985b911129b449734bbf63749a03f6ef69b8ca37f2ecd74d46fabef1f
          imagePullPolicy: IfNotPresent
          env:
            - name: PUID
              value: "0"
            - name: PGID
              value: "0"
            - name: TZ
              value: "America/Los_Angeles"
          ports:
            - containerPort: 8989
              protocol: TCP
          volumeMounts:
            - mountPath: /config
              name: config
            - mountPath: /data
              name: data
          resources:
            requests:
              cpu: 250m
              memory: 500Mi
            limits:
              memory: 1Gi
          livenessProbe:
            httpGet:
              port: 8989
              path: /ping
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 5
            failureThreshold: 3
          readinessProbe:
            httpGet:
              port: 8989
              path: /ping
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3
      restartPolicy: Always
      volumes:
        - name: data
          nfs:
            path: /data
            server: 192.168.1.52
            readOnly: false
        - name: tarsnapper-config
          configMap:
            name: tarsnapper-config
        - name: backup-key
          secret:
            secretName: backup-key
        - name: backup-tmpdir
          emptyDir:
            medium: Memory
        - name: tarsnap-cache
          emptyDir: { }
  volumeClaimTemplates:
    - metadata:
        name: config
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: tarsnapper-config
data:
  tarsnapper.conf: |
    deltas: 1d 7d 30d 90d
    target: /rpi5-sonarr/$name-$date
    jobs:
      sonarr:
        source: /backup
