apiVersion: v1
kind: Namespace
metadata:
  name: trailarr
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: trailarr
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: trailarr
  project: default
  source:
    repoURL: {{ .Values.spec.source.repoURL }}
    targetRevision: {{ .Values.spec.source.branch }}
    path: rpi5/trailarr
