apiVersion: batch/v1
kind: CronJob
metadata:
  name: teslamate-backup
spec:
  schedule: "14 8 * * *"
  concurrencyPolicy: Forbid
  jobTemplate:
    spec:
      template:
        spec:
          initContainers:
            - name: pgdump
              image: postgres:17.2@sha256:269c12fd770bc805ca0e8c77c7882d14d96be770b6839c8d17b871034361e74a
              imagePullPolicy: IfNotPresent
              command:
                - sh
                - -c
                - |
                  pg_dump -p 5432 teslamate > /backup/backup.sql
              env:
                - name: PGHOST
                  valueFrom:
                    secretKeyRef:
                      name: teslamate-cluster-superuser
                      key: host
                - name: PGUSER
                  valueFrom:
                    secretKeyRef:
                      name: teslamate-cluster-superuser
                      key: user
                - name: PGPASSWORD
                  valueFrom:
                    secretKeyRef:
                      name: teslamate-cluster-superuser
                      key: password
              volumeMounts:
                - mountPath: /backup
                  name: backup
          containers:
            - name: restic
              image: creativeprojects/resticprofile:0.29.0@sha256:9fbca0c5fab32b15a815d63f82964ce54d57836bbd032f54c278f5a369465ea6
              imagePullPolicy: IfNotPresent
              command: [ "resticprofile", "backup" ]
              env:
                - name: RESTIC_REST_USERNAME
                  value: "teslamate"
                - name: RESTIC_REST_PASSWORD
                  valueFrom:
                    secretKeyRef:
                      key: restPassword
                      name: secrets
              volumeMounts:
                - mountPath: /resticprofile/profiles.yaml
                  name: profile
                  subPath: profiles.yaml
                - mountPath: /resticprofile/password
                  name: secrets
                  subPath: password
                - mountPath: /backup
                  name: backup
          restartPolicy: OnFailure
          volumes:
            - name: backup
              emptyDir: { }
            - name: profile
              configMap:
                name: resticprofile
            - name: secrets
              secret:
                secretName: secrets
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: resticprofile
data:
  profiles.yaml: |
    version: "1"

    default:
      repository: "rest:https://restic.anshulg.com/teslamate/"
      initialize: true
      password-file: "/resticprofile/password"
      compression: "max"
      force-inactive-lock: true

      env:
        RESTIC_HOST: "teslamate"

      retention:
        before-backup: false
        after-backup: true
        keep-daily: 7
        keep-weekly: 4
        keep-monthly: 1
        prune: true
        host: false

      backup:
        source:
          - "/backup"
        tag:
          - "teslamate"
