apiVersion: cert-manager.io/v1
kind: Certificate
metadata:
  name: teslamate-cert
  namespace: teslamate
spec:
  secretName: teslamate-cert-tls
  commonName: teslamate.local
  dnsNames:
    - teslamate.local
    - teslamate.internal
  duration: 2160h0m0s
  renewBefore: 720h0m0s
  privateKey:
    algorithm: ECDSA
    size: 384
    rotationPolicy: Always
  subject:
    organizations:
      - Anshul Gupta
    organizationalUnits:
      - rpi5
    provinces:
      - California
    countries:
      - US
  issuerRef:
    group: cas-issuer.jetstack.io
    kind: GoogleCASClusterIssuer
    name: anshulg-ca
