apiVersion: v1
kind: Namespace
metadata:
  name: node-feature-discovery
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: node-feature-discovery
  namespace: argocd
spec:
  project: internal
  source:
    chart: node-feature-discovery
    repoURL: https://kubernetes-sigs.github.io/node-feature-discovery/charts
    targetRevision: 0.17.1
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: node-feature-discovery
  syncPolicy:
    automated: {}
---
apiVersion: v1
kind: Namespace
metadata:
  name: inteldeviceplugins-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: dp-operator
  namespace: argocd
spec:
  project: internal
  source:
    chart: intel-device-plugins-operator
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.32.0
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: inteldeviceplugins-system
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: intel-gpu
  namespace: argocd
spec:
  project: internal
  source:
    chart: intel-device-plugins-gpu
    repoURL: https://intel.github.io/helm-charts/
    targetRevision: 0.32.0
    helm:
      parameters:
        - name: nodeFeatureRule
          value: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: inteldeviceplugins-system
