apiVersion: v1
kind: Namespace
metadata:
  name: tailscale
---
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: tailscale-operator
  namespace: argocd
  finalizers:
    - resources-finalizer.argocd.argoproj.io
spec:
  project: internal
  source:
    chart: tailscale-operator
    repoURL: https://pkgs.tailscale.com/helmcharts
    targetRevision: 1.80.0
    helm:
      values: |
        apiServerProxyConfig:
          mode: "true"
  destination:
    server: {{ .Values.spec.destination.server }}
    namespace: tailscale
  syncPolicy:
    automated: {}
