apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: protonmail
  labels:
    app: protonmail
spec:
  replicas: 1
  selector:
    matchLabels:
      app: protonmail
  serviceName: protonmail
  template:
    metadata:
      name: protonmail
      labels:
        app: protonmail
    spec:
      containers:
        - name: protonmail
          image: shenxn/protonmail-bridge:3.17.0-1@sha256:e96a7d1e9c96b111e89f3a6c1e8e155dcf413e3d7bb63211478fdd290aeed76c
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 25
              protocol: TCP
              name: smtp
            - containerPort: 143
              protocol: TCP
              name: imap
          volumeMounts:
            - mountPath: /root
              name: data
      restartPolicy: Always
      nodeSelector:
        kubernetes.io/arch: amd64
  volumeClaimTemplates:
    - metadata:
        name: data
      spec:
        accessModes: [ "ReadWriteOnce" ]
        resources:
          requests:
            storage: 5Gi
